repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v5.0.0"
    hooks:
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-json
        exclude: ^({{cookiecutter.project_name}}/\.devcontainer/devcontainer\.json|\.devcontainer/devcontainer\.json|{{cookiecutter.project_name}}/)$
      - id: pretty-format-json
        exclude: ^({{cookiecutter.project_name}}/\.devcontainer/devcontainer\.json|\.devcontainer/devcontainer\.json|{{cookiecutter.project_name}}/)$
        args: [--autofix]
      - id: check-toml
        exclude: ^{{cookiecutter.project_name}}/
      - id: check-yaml
        exclude: ^{{cookiecutter.project_name}}/

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "v0.6.3"
    hooks:
      - id: ruff
        args: [--exit-non-zero-on-fix, --config=pyproject.toml]
        exclude: ^{{cookiecutter.project_name}}
      - id: ruff-format
        args: [--config=pyproject.toml]
        exclude: ^{{cookiecutter.project_name}}
