[project]
site_name = "cookiecutter-uv"
repo_url = "https://github.com/fpgmaas/cookiecutter-uv"
site_url = "https://fpgmaas.github.io/cookiecutter-uv"
site_description = "A cookiecutter template for Python projects that use uv for its dependency management"
site_author = "Florian Maas"
edit_uri = "edit/main/docs/"
repo_name = "fpgmaas/cookiecutter-uv"
copyright = "Maintained by <a href='https://fpgmaas.com'>Florian</a>."

nav = [
    { "Home" = "index.md" },
    { "Features" = [
        { "Features" = "features/index.md" },
        { "CI/CD with Github Actions" = "features/cicd.md" },
        { "Linting & code quality" = "features/linting.md" },
        { "Makefile" = "features/makefile.md" },
        { "Dependency management with uv" = "features/uv.md" },
        { "Publishing to PyPI" = "features/publishing.md" },
        { "Testing with Pytest" = "features/pytest.md" },
        { "Test coverage with codecov" = "features/codecov.md" },
        { "Documentation with MkDocs" = "features/mkdocs.md" },
        { "Compatibility testing with Tox" = "features/tox.md" },
        { "Containerization with Docker or Podman" = "features/docker.md" },
        { "Devcontainer with VSCode" = "features/devcontainer.md" }
    ]},
    { "Tutorial" = "tutorial.md" },
    { "Prompt Arguments" = "prompt_arguments.md" }
]

extra_css = ["stylesheets/extra.css"]

[project.theme]
favicon = "static/logo.svg"
language = "en"
features = [
    "announce.dismiss",
    "content.code.annotate",
    "content.action.edit",
    "content.action.view",
    "content.code.copy",
    "content.code.select",
    "content.footnote.tooltips",
    "content.tabs.link",
    "content.tooltips",
    "navigation.footer",
    "navigation.indexes",
    "navigation.instant",
    "navigation.instant.prefetch",
    "navigation.path",
    "navigation.prune",
    "navigation.top",
    "navigation.tracking",
    "search.highlight",
]

logo = "static/logo.svg"

[project.theme.icon]
previous = "fontawesome/solid/angle-left"
next = "fontawesome/solid/angle-right"
repo = "fontawesome/brands/github"

#[project.theme.font]
#text = "Inter"
#code = "Jetbrains Mono"


[[project.theme.palette]]
media = "(prefers-color-scheme)"
toggle.icon = "material/brightness-auto"
toggle.name = "Switch to light mode"

[[project.theme.palette]]
media = "(prefers-color-scheme: light)"
scheme = "astral-light"
toggle.icon =  "material/brightness-7"
toggle.name = "Switch to dark mode"

[[project.theme.palette]]
media = "(prefers-color-scheme: dark)"
scheme = "astral-dark"
toggle.icon =  "material/brightness-4"
toggle.name = "Switch to system preference"

[[project.extra.social]]
icon = "fontawesome/brands/github"
link = "https://github.com/fpgmaas/cookiecutter-uv"

[[project.extra.social]]
icon = "fontawesome/brands/python"
link = "https://pypi.org/project/cookiecutter-uv/"
