site_name: {{cookiecutter.project_name}}
repo_url: https://github.com/{{cookiecutter.author_github_handle}}/{{cookiecutter.project_name}}
site_url: https://{{cookiecutter.author_github_handle}}.github.io/{{cookiecutter.project_name}}
site_description: {{cookiecutter.project_description}}
site_author: {{cookiecutter.author}}
edit_uri: edit/main/docs/
repo_name: {{cookiecutter.author_github_handle}}/{{cookiecutter.project_name}}
copyright: Maintained by <a href="https://github.com/{{cookiecutter.author_github_handle}}">{{cookiecutter.author}}</a>.

nav:
  - Home: index.md
  - API Reference:
    - {{cookiecutter.project_slug}}.foo: api_reference/index.md
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [{{cookiecutter.project_slug}}]
theme:
  name: material
  icon:
    repo: fontawesome/brands/github
    edit: material/pencil
    view: material/eye
    theme:
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - content.tabs.link
    - content.tooltips
    - header.autohide
    - navigation.expand
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.prune
    - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: black
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
# Extensions
markdown_extensions:
  - abbr
  - admonition
  - pymdownx.details
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      pygments_style: monokai
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      normalize_issue_symbols: true
      repo_url_shorthand: true
      user: {{cookiecutter.author_github_handle}}
      repo: {{cookiecutter.project_name}}
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      auto_append:
        - includes/mkdocs.md
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/katex.js
  - https://unpkg.com/katex@0/dist/katex.min.js
  - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js

extra_css:
  - https://unpkg.com/katex@0/dist/katex.min.css

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/{{cookiecutter.author_github_handle}}/{{cookiecutter.project_name}}
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/{{cookiecutter.project_name}}

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
