name: release-main

on:
  release:
    types: [published]

jobs:
{% if cookiecutter.publish_to_pypi == "y" %}
  set-version:
    runs-on: ubuntu-24.04
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push changes
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main

      - name: Export tag
        id: vars
        run: {% raw %}echo tag=${GITHUB_REF#refs/*/} >> $GITHUB_OUTPUT{% endraw %}
        if: {% raw %}${{ github.event_name == 'release' }}{% endraw %}

      - name: Update project version
        run: |
          sed -i "s/^version = \".*\"/version = \"$RELEASE_VERSION\"/" pyproject.toml
        env:
          RELEASE_VERSION: {% raw %}${{ steps.vars.outputs.tag }}{% endraw %}
        if: {% raw %}${{ github.event_name == 'release' }}{% endraw %}

      - name: Upload updated pyproject.toml
        uses: actions/upload-artifact@v4
        with:
          name: pyproject-toml
          path: pyproject.toml

      - name: Commit pyproject.toml version update
        uses: stefanzweifel/git-auto-commit-action@v6
        with:
          commit_message: {% raw %}"Update version to ${{ steps.vars.outputs.tag }}"{% endraw %}
          file_pattern: pyproject.toml
        if: {% raw %}${{ github.event_name == 'release' }}{% endraw %}

  publish:
    runs-on: ubuntu-latest
    needs: [set-version]
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Set up the environment
        uses: ./.github/actions/setup-python-env

      - name: Download updated pyproject.toml
        uses: actions/download-artifact@v4
        with:
          name: pyproject-toml

      - name: Build package
        run: uv build

      - name: Publish package
        run: uv publish
        env:
          UV_PUBLISH_TOKEN: {% raw %}${{ secrets.PYPI_TOKEN }}{% endraw %}
{% endif %}
{%- if cookiecutter.mkdocs == "y" %}
  deploy-docs:
    {%- if cookiecutter.publish_to_pypi == "y" %}
    needs: publish
    {%- endif %}
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Set up the environment
        uses: ./.github/actions/setup-python-env

      - name: Deploy documentation
        run: uv run mkdocs gh-deploy --force
{% endif %}
